services:
  ollama-intel-gpu:
    image: ghcr.io/open-webui/open-webui
    container_name: ollama-intel-gpu
    restart: always
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - ollama-intel-gpu:/root/.ollama
    environment:
      - ONEAPI_DEVICE_SELECTOR=level_zero:3
      - IPEX_LLM_NUM_CTX=16384
  ollama-webui:
    image: ghcr.io/open-webui/open-webui
    container_name: ollama-webui
    volumes:
      - ollama-webui:/app/backend/data
    depends_on:
      - ollama-intel-gpu
    ports:
      - 9901:8080
    environment:
      - OLLAMA_BASE_URL=http://ollama-intel-gpu:11434
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
volumes:
  ollama-webui: {}
  ollama-intel-gpu: {}
